'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShopDetails

    '''<summary>
    '''divShopBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShopBanner As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgShopLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgShopLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblShopName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShopName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreatedAt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedAt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnFollow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFollow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptShopProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptShopProducts As Global.System.Web.UI.WebControls.Repeater
End Class
