'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StoreProductsControl

    '''<summary>
    '''lblProductMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnShowAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowAddProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddProduct As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNameError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNameError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPriceError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStock As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblStockError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStockError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtThreshold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThreshold As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblThresholdError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThresholdError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCategoryError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuProductImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuProductImages As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblImageError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProducts As Global.System.Web.UI.WebControls.Repeater
End Class
