'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageShop

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lnkDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDashboard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProducts As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOrders As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mvShop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvShop As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewDashboard As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblShopName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShopName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreatedAt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedAt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShopDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShopDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewProducts As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''iframeProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iframeProducts As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''viewOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewOrders As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''rptOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOrders As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''viewSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSettings As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''chkIsActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIsActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsActive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSaveSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtEditShopName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditShopName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtThemeColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThemeColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fuLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuLogo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''imgLogoPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogoPreview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''fuBanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuBanner As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''imgBannerPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBannerPreview As Global.System.Web.UI.WebControls.Image
End Class
